### ISSUE TITLE
Fatal error: Class 'SSRS\Soap\NTLM' not found

### ISSUE THREAD

**Issue by emigort** [ChartBlocks/php-ssrs#1]
Hello, I'm trying to use your library, but I cant get it work, how I have to set the Name Spaces?

PHP Version 5.4
WebServer: Centos 6.4
MSSQL Server 2008 R2

```
require('library/SSRS/Report.php');
$ssrs = new \SSRS\Report(SERVICE_URL,$options);
$ssrs->listChildren('/Report Folder');
```

I got: `Fatal error: Class 'SSRS\Soap\NTLM' not found in ...`

I'm using Basic Authentication 

How Am I setup the library to load all the required classes.

sorry for post it here, but I don't now how to contact you in regard with this topic, and thanks for any help you  could give me

**Comment by arronwoods** [comment]
Hi emigort,

Sounds like you're using SSRS without composer or another autoloader. We don't put require statements at the top of our classes, so the library won't grab them out the box.

I'll leave this ticket open for now, as it might be worth us adding a tiny autoloader just in case, but I'd highly recommend you use Composer (https://getcomposer.org) to install the php-ssrs library.

Thanks,

Arron

**Comment by arronwoods** [comment]
Not sure its worth including an autoloader in php-ssrs so I've updated the README a bit instead to re-enforce the need for one.
