### ISSUE TITLE
Content-Length header must not be set

### ISSUE THREAD

**Issue by SmokeyBrandie** [ChartBlocks/php-ssrs#10]
The content length hader must not be set since CURL sets the length automatically

So I suggest to remove the following line:
$headers[] = 'Content-Length: ' . strlen($data);

From function generateHeaders in File NTLM.php

**Comment by arronwoods** [comment]
Pushed up to master. Out of interest, was the calculated value incorrect, or were you getting two headers in the request?

**Comment by arronwoods** [comment]
P.S. Happy to accept pull requests if you'd like to fork the lib and make changes faster than I can get back to you.
