### ISSUE TITLE
Toggle Item

### ISSUE THREAD

**Issue by afvalzak** [ChartBlocks/php-ssrs#12]
Can you explain how I can use the toggleItem method?

I can execute it just fine:

```
$ssrs->printr($ssrs -> toggleItem("24iT0R0x0"));
```

returns:

```
stdClass Object
(
    [Found] => 1
)
```

but nothing happens. 

edit: 
Ok, rerendering after the toggle helps a lot. I should really post to this github everytime I have some sort of a problem because it seems to be fixed right after ;) .

**Comment by arronwoods** [comment]
Glad to hear you managed to sort it! :)
