### ISSUE TITLE
SSRS_SOAP_EXCEPTION not found

### ISSUE THREAD

**Issue by afvalzak** [ChartBlocks/php-ssrs#13]
The class SSRS_SOAP_EXCEPTION is not in the zip but is referenced in the NTML.php file on line 145
My error:

```
Fatal error: Class 'SSRS\Soap\SSRS_Soap_Exception' not found in *snip* on line 143
```

I have changed this from:

```
throw new SSRS_Soap_Exception('CURL error: ' . curl_error($handle), curl_errno($handle));
```

to:

```
throw new Exception('CURL error: ' . curl_error($handle), curl_errno($handle));
```

Which works, so maybe it's something you should look into.

**Comment by arronwoods** [comment]
Thanks @afvalzak, I've committed a fix and tagged a new release, version 1.0.8.
