### ISSUE TITLE
Zend Server Config Assistance

### ISSUE THREAD

**Issue by JWholey** [ChartBlocks/php-ssrs#2]
Could you help me to understand how I would install this package into a Zend Server environment?

I am running Zend Server 6.1.0 on Windows Server 2008 R2.
My SSRS is on another server which is running SQL Server 2008 R2 SSRS under Windows Server 2008 R2.

The PHP guts appear to live in the following folder: 
C:\Program Files (x86)\Zend\ZendServer\bin 

Any assistance you could give me in "autoloading" this package would be appreciated, as I am not using composer to do the install.

Joe

**Comment by arronwoods** [comment]
Hi Joe,

Sure, it shouldn't be too different to any other environment hopefully. How familiar are you with PHP and running it on Windows? 

Your best bet would be to checkout the library to a folder somewhere, and try one of the samples. Have you had any luck with those?

Open up samples/ListChildren.php and modify the username and password (lines 8 & 9) to a user with access to your server, and change the URL "http://localhost" to that of your server (this could be a local or remote IP) on line 10.

If those settings are all correct, and you've enabled access to the SOAP API something like this in a command prompt should give you a list of reports on the server:

``` bash
C:\path\to\php-ssrs\> php samples/ListChildren.php
```

Any errors you encounter, paste them here and I'll do my best to help.

**Comment by JWholey** [comment]
Thanks rb!

I appreciate your quick response. I am spending some time learning Zend configuration and Zend application.

This afternoon, I hope to be able to try your suggestions.

Best Regards,

Joe Wholey
Software Programmer / DB Admin
West Central Behavioral Health
"...we commit ourselves to provide services that
are safe, effective, client-centered, timely and efficient."
email:jwholey@wcbh.org

**Comment by JWholey** [comment]
Hi RB,

I have abandoned ZendServer due to its new monetary requirements.

1)I uninstalled it and put XAMPP Version 1.8.3 on my Windows 2008 R2 64-bit server, in the C:\XAMPP folder.

2)I extracted the php-ssrs-master.zip file into the c:\xampp\htdocs folder

3)I ran the following URL in Internet Explorer 11:  [http://localhost/php-ssrs-master/samples/listchildren.php] and got the following result.

Warning: require(C:\xampp\htdocs\php-ssrs-master\samples/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\php-ssrs-master\samples\ListChildren.php on line 3

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\php-ssrs-master\samples/../vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\php-ssrs-master\samples\ListChildren.php on line 3

Questions:
A)There are 7 autolaod.php files in different folders within c:\xampp. Which one is my “vendor” (There is no subfolder named “vendor”)?
B)How should my folder structure be organized under htdocs, so that I can have a single Reporting Hub project which runs SSRS reports?

Any guidance you can offer me (a newbie to PHP) would be appreciated.

Best Regards,

Joe Wholey
Software Programmer / DB Admin
West Central Behavioral Health
"...we commit ourselves to provide services that
are safe, effective, client-centered, timely and efficient."
email:jwholey@wcbh.org

**Comment by arronwoods** [comment]
Hi Joe,

Sounds like you're making progress. php-ssrs uses a tool called composer to download and manage its dependencies.

Their docs explain it better than I can, so take a look at those: https://getcomposer.org/doc/00-intro.md#installation-windows

You will need to install composer, then run composer within the php-ssrs directory (where the composer.json file sits).

Hope this helps.

**Comment by JWholey** [comment]
Thanks – I am making progress….

I am now stuck on setting a valid WSDL temporary folder. Should I create a /tmp/ folder beneath the project folder, or beneath the /Soap/ folder?

Joe

**Comment by JWholey** [comment]
…have now set a Temp folder at C:\TEMPWSDL after learning about the double slash (\) needed with windows filespecs, but am getting a more difficult XML parsing error:

Fatal error: Uncaught SoapFault exception: [Client] Class 'SSRS\Soap\SimpleXMLElement' not found in C:\xampp\htdocs\php-ssrs-master\library\SSRS\Soap\ServerException.php:12

Any ideas? Perhaps a version conflict with SSRS 2008 R2?

From: Joseph Wholey
Sent: Thursday, July 17, 2014 2:57 PM
To: 'ChartBlocks/php-ssrs'; ChartBlocks/php-ssrs
Subject: RE: [php-ssrs] Zend Server Config Assistance (#2)

Thanks – I am making progress….

I am now stuck on setting a valid WSDL temporary folder. Should I create a /tmp/ folder beneath the project folder, or beneath the /Soap/ folder?

Joe

**Comment by arronwoods** [comment]
Hi Joe,

I'm sure you gave up by now, but the error you were getting was just fixed in issue #6.

**Comment by JWholey** [comment]
Hi,

Thanks for following through. I have decided to give this latest download another few hours before I give up and go forward with ASP.NET.

Can you help me understand how to make the autoload.php reference work in listChildren.php?

Do I need to make a php autoload.php file and stick it somewhere in the samples folder?

Best regards,

Joe Wholey
Software Programmer / DB Admin
West Central Behavioral Health
-Cell:-603-717-6964 Office:603-448-0126 x2166
“…we commit ourselves to provide services that
Are safe, effective, client-centered, timely and efficient.”

**Comment by arronwoods** [comment]
autoload.php is generated for you if you use Composer.

Composer is a package manager for PHP, it downloads and manages dependencies. Its really easy to use, and is free. Take a look at https://getcomposer.org/doc/00-intro.md for a "Getting started" guide.

Once you've installed php-ssrs using composer, you will have an autoload file and the examples should make more sense.

**Comment by JWholey** [comment]
Hi rb,

Thanks for your patience with all of this. I have installed Composer and struggled to install the chartblocks successfully.

Now I am receiving this error:

C:\xampp\htdocs\php-ssrs>php samples/listchildren.php

Fatal error: Uncaught exception 'Exception' with message 'String could not be pa
rsed as XML' in C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSR
S\Soap\ServerException.php:12
Stack trace:
#0 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\Server
Exception.php(12): SimpleXMLElement->__construct('')
#1 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\NTLM.p
hp(148): SSRS\Soap\ServerException::fromResponse('')
#2 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\NTLM.p
hp(112): SSRS\Soap\NTLM->callCurl('http://server6/...')
#3 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\NTLM.p
hp(33): SSRS\Soap\NTLM->fetchWSDL()
#4 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Report.php(
451): SSRS\Soap\NTLM->init()
#5 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Report.php(
125): SSRS\Report->createNTLMClient('ReportService20...', true)
#6 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library in C:\xampp\htdo
cs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\ServerException.php on
line 12

C:\xampp\htdocs\php-ssrs>

Could this be because the server’s root is configured to return the IIS7  banner instead of an SSRS screen?

The server returns the SSRS content only under URL : http://server6/Reports and not under http://server6/ or http://server6/reportserver

Any ideas?

Thanks muchly!

**Comment by arronwoods** [comment]
From the stack trace it looks like the server isn't returning anything:

#0 
C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\Server
Exception.php(12): SimpleXMLElement->__construct('')
#1 
C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\NTLM.p
hp(148): SSRS\Soap\ServerException::fromResponse('')
#2 
C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\NTLM.p
hp(112): SSRS\Soap\NTLM->callCurl('http://server6/...')

See the argument to fromReponse is empty (unless you modified the stack 
trace to post it on github)?

What happens if you use http://server6/Reports as the server URL?

**Comment by JWholey** [comment]
I get this error:

Fatal error: Uncaught exception 'Exception' with message 'String could not be pa
rsed as XML' in C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSR
S\Soap\ServerException.php:12
Stack trace:
#0 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\Server
Exception.php(12): SimpleXMLElement->__construct('')
#1 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\NTLM.p
hp(148): SSRS\Soap\ServerException::fromResponse('')
#2 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\NTLM.p
hp(112): SSRS\Soap\NTLM->callCurl('http://server6/...')
#3 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\NTLM.p
hp(33): SSRS\Soap\NTLM->fetchWSDL()
#4 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Report.php(
451): SSRS\Soap\NTLM->init()
#5 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Report.php(
125): SSRS\Report->createNTLMClient('ReportService20...', true)
#6 C:\xampp\htdocs\php-ssrs\vendor\chartblocks\php-ssrs\library in C:\xampp\htdo
cs\php-ssrs\vendor\chartblocks\php-ssrs\library\SSRS\Soap\ServerException.php on
line 12

C:\xampp\htdocs\php-ssrs>

**Comment by arronwoods** [comment]
What happens if you visit http://server6/Reports/ReportService2010.asmx 
in your browser? Or any combination of the URLs you think the report 
server could be listening on, but with ReportService2010.asmx on the end?

Its when trying to grab that file that the exception is being thrown. 
Without digging further its hard to know what is going wrong, but a good 
test would be knowing that the file can be served to a browser.

**Comment by JWholey** [comment]
Hi rb,

I can’t thank you enough for your guidance. I work here WCBH as the only programmer, so learning to reach out and connect to others who can help is important.

I will try different URLs , because I believe that you are correct that this is a server communication issue, not anything going on with the php stuff.

If ListChildren were to work, should the url be pointing to a “folder” in the SSRS server? The http://Server6/Reports URL shows several different folders of SSRS projects I have tutorialed.
Should I be pointing further into one of those folders to list their children’s reports? (in other words, the “Reports” location seems to be made of other subfolders, not reports.

Yours in debt,

Joe Wholey

**Comment by JWholey** [comment]
Ooooh- forget to mention that the SSRS is running SQL Server 2008 R2, not 2010.

**Comment by arronwoods** [comment]
Not a problem, sorry I can't help more, I'm not familiar with SSRS from 
the server administration side, only consuming it as a client.

Server 2008 R2 is fine, despite the reference to 2010 in the filename: 
https://msdn.microsoft.com/en-us/library/reportservice2010%28v=sql.105%29.aspx. 
This confused me too!

To drill down in to report folders, you change the first argument of 
listChildren. You always connect to SSRS on the same URL, then adapt the 
path to the children you would like to list:

$ssrs = new \SSRS\Report('http://server6/reportserver/', $options);
$topLevel = $ssrs->listChildren('/Reports/', true);
$subLevel = $ssrs->listChildren('/Reports/Subfolder', true);

**Comment by JWholey** [comment]
Hi rb!

Here is some useful (I think) information about my problem:

·         I set my SSRS Server name to something different, and then adjusted the listchildren.php to match.

·         I went on the php machine and used the <NewServerURL>/ReportService2010.asmx in my browser and BINGO – out came a wicked lot of xml.

·         I reran the ListChildren with a display at line 12 of ServerException.php, and a URL display at line 124 of NTLM.php, and confirmed that they were correct BUT

·         It still gives the ‘String could not be parsed as XML’ error.

I think we are really close…., and I hope this helps someone.

Best Regards,
Joe Wholey

**Comment by JWholey** [comment]
Hi rb,

I have now determined that the empty response from host is due to an HTTP 401 status: Authorization.

I added an echo to line 149 of the NTLM.php and got the $httpCode as 401.

If you have any pointers on how to beat this, I would be grateful.

I'll keep chipping a bit more.

Regards,

Joe Wholey
Software Programmer / DB Admin
West Central Behavioral Health
-Cell:-603-717-6964 Office:603-448-0126 x2166
"...we commit ourselves to provide services that
Are safe, effective, client-centered, timely and efficient."

---

IMPORTANT NOTICE REGARDING THIS ELECTRONIC MESSAGE- This message is intended for the use of the person to whom it was addressed and may contain information that is privileged, confidential and protected from disclosure under applicable law, including but not limited to NH RSA 151:13a and NH RSA 329.29a. If you are not the intended recipient, your use of this message for any purpose is strictly prohibited. If you have received this communication in error, please delete the message and notify the sender so that we may correct our records.

**Comment by JWholey** [comment]
Hi rb,

Thanks to you, this issue has been resolved. I found some valid credentials on the report server database, and the ListChildren.php worked great!

You can sleep well, knowing you have done your good deed for the day!

I am very grateful,

Joe Wholey

From: Joseph Wholey
Sent: Tuesday, March 10, 2015 4:08 PM
To: ChartBlocks/php-ssrs (reply@reply.github.com)
Subject: Authorization Issue

Hi rb,

I have now determined that the empty response from host is due to an HTTP 401 status: Authorization.

I added an echo to line 149 of the NTLM.php and got the $httpCode as 401.

If you have any pointers on how to beat this, I would be grateful.

I'll keep chipping a bit more.

Regards,

Joe Wholey
Software Programmer / DB Admin
West Central Behavioral Health
-Cell:-603-717-6964 Office:603-448-0126 x2166
"...we commit ourselves to provide services that
Are safe, effective, client-centered, timely and efficient."

---

IMPORTANT NOTICE REGARDING THIS ELECTRONIC MESSAGE- This message is intended for the use of the person to whom it was addressed and may contain information that is privileged, confidential and protected from disclosure under applicable law, including but not limited to NH RSA 151:13a and NH RSA 329.29a. If you are not the intended recipient, your use of this message for any purpose is strictly prohibited. If you have received this communication in error, please delete the message and notify the sender so that we may correct our records.

**Comment by arronwoods** [comment]
That is great news, glad you managed to find a solution!

I'll try to set up an SSRS instance again, and work on getting better 
error messages through to users when authentication fails.

**Comment by JWholey** [comment]
Hi rb,

Thanks again for your all your help.

Now that I am considering what to do with this new capability, can you recommend a couple of things for me:

·         A book or resource for learning PHP and its object model (I struggle to understand how the folder hierarchy or path of different modules relate to each other)

·         An open source PHP project to use for a Portal or Intranet (The less configuring and/or coding the better) where I can use the SSRS to serve reports to?

Thanks again for your mentoring!

Best Regards,

Joe Wholey
Software Programmer / DB Admin
West Central Behavioral Health
-Cell:-603-717-6964 Office:603-448-0126 x2166
“…we commit ourselves to provide services that
Are safe, effective, client-centered, timely and efficient.”

**Comment by arronwoods** [comment]
I'm afraid I can't think of either off the cuff, this website springs to 
mind though:
http://www.phptherightway.com/

**Comment by JWholey** [comment]
SELECT DISTINCT
'ClientName' = cl.lastname_vc+', '+cl.firstname_vc+' ['+cl.clientcode_c+']',
ps.psplandescript_vc 'Ins',
cps.priority_n 'Priority'
--cps.startdate_d,
--cps.enddate_d,
from ar.cpsplan cps
join ar.psplanmaster ps on cps.psplanmasterid_c = ps.uniqueid_c
join ar.client cl on cps.clientid_c = cl.uniqueid_c
where
ps.pscode_c = 'AMBETTER'
and cps.suspenduse_c = 'N'
IMPORTANT NOTICE REGARDING THIS ELECTRONIC MESSAGE- This message is intended for the use of the person to whom it was addressed and may contain information that is privileged, confidential and protected from disclosure under applicable law, including but not limited to NH RSA 151:13a and NH RSA 329.29a. If you are not the intended recipient, your use of this message for any purpose is strictly prohibited. If you have received this communication in error, please delete the message and notify the sender so that we may correct our records.
