### ISSUE TITLE
_cacheExpiry not set

### ISSUE THREAD

**Issue by rbro** [ChartBlocks/php-ssrs#26]
When using NTLM, I noticed that the WSDL file was being re-cached on every request.

Looking in SSRS\Soap\NTLM.php, I see that _cacheExpiry defaults to null, and the function setCacheExpiry() is never called.

Should this function be called in the constructor or elsewhere?

Thanks for your help.

**Comment by arronwoods** [comment]
Hi rbro,

Good spot, I've just tagged 1.0.11 with this option set to 86400 seconds by default.

In this new version you can also set the option "cache_wsdl_expiry" in the Report constructor, or the NTML constructor, to set the expiry time without having to mess around.
