### ISSUE TITLE
CURL error: Could not resolve proxy

### ISSUE THREAD

**Issue by widiramadhan** [ChartBlocks/php-ssrs#29]
how to solve this error? please help me

Fatal error: Uncaught exception 'SSRS\Soap\Exception' with message 'CURL error: Could not resolve proxy: http=nebula' in C:\xamppPHP5\htdocs\php-ssrs\library\SSRS\Soap\NTLM.php:165 Stack trace: #0 C:\xamppPHP5\htdocs\php-ssrs\library\SSRS\Soap\NTLM.php(135): SSRS\Soap\NTLM->callCurl('http://172.22.0...', '<?xml version="...', 'http://schemas....') #1 [internal function]: SSRS\Soap\NTLM->__doRequest('<?xml version="...', 'http://172.22.0...', 'http://schemas....', 1, 0) #2 C:\xamppPHP5\htdocs\php-ssrs\library\SSRS\Report.php(240): SoapClient->__call('GetItemDefiniti...', Array) #3 C:\xamppPHP5\htdocs\php-ssrs\library\SSRS\Report.php(240): SSRS\Soap\NTLM->GetItemDefinition(Array) #4 C:\xamppPHP5\htdocs\php-ssrs\samples\GetItemDefinition.php(13): SSRS\Report->getItemDefinition('/Pages') #5 {main} thrown in C:\xamppPHP5\htdocs\php-ssrs\library\SSRS\Soap\NTLM.php on line 165

**Comment by arronwoods** [comment]
Are you trying to use a proxy for the curl connection?

If not this might help:
https://stackoverflow.com/questions/11144706/php-curl-error-could-not-resolve-proxy

**Comment by widiramadhan** [comment]
my problem solved, i try add curl_setopt($handle, CURLOPT_HTTPPROXYTUNNEL, false); in NTLM.php

**Comment by Ashish65649** [comment]
rrhh
