### ISSUE TITLE
Html - rendering images 

### ISSUE THREAD

**Issue by acpbytron** [ChartBlocks/php-ssrs#3]
I m having issues rendering a report to html as the report contains charts which are rendered as images on the SSRS server.  The browser into which the report is rendered does not have authorization to access the charts (images) in the report so they fail to load resulting in a page of blank squares !

Is there a way around this problem ?  Any session or cookie settings which will pass the authenticated session back to the browse ?

Thank you.

**Comment by arronwoods** [comment]
Hey @acpbytron,

I did find a way around this, I just can't remember what it was.

I think you have to rewrite the URL to the image to include the SSRS render token. I'll try to dig out the code I used and update this request.

With any luck its already in, or can be put in to, the php-ssrs lib.

**Comment by arronwoods** [comment]
OK, so I was using the following device info to change where the resources point:

``` php
<?php
$deviceInfo = array(
  'ReplacementRoot' => 'ssrsRR//',
  'ResourceStreamRoot' => "http://url/to/stream/proxy.php?executionID=$executionID&format=$format",
  'StreamRoot' => "http://url/to/stream/proxy.php?executionID=$executionID&format=$format"
);
```

Then in my proxy.php file, I'd continue the SSRS session and request the image from SSRS like this:

``` php
$response = $ssrs->renderStream($format, $streamId, $deviceInfo);
```

And return it to the browser like this:

``` php
header('Content-type: ' . $response->MimeType);
header('Cache-Control: no-cache');
header('Pragma: no-cache');
echo ($response->Result);
exit(0);

```

Does that make any sense? It's quite long winded, would be nice if we could add something to the php-ssrs library.

**Comment by acpbytron** [comment]
Thanks for getting back to me.  I will give it a go ...

Any chance of adding  a sample proxy.php to the repository ?

Cheers,
Andy

**Comment by acpbytron** [comment]
Hi @rb-cohen 

I have been away so have only just started to look at this ... have been trying to set up a proxy as described above but have had limited success ...

I have the image requests in the report redirected to proxy.php using the deviceInfo -

``` php
$deviceInfo = array(
  'ReplacementRoot' => 'reportProxy.php?dest=',
  'ResourceStreamRoot' => "http://lserver/dashboard/proxy.php?executionID=".$executionID."&format=HTML4.0&streamID=",
  'StreamRoot' => "http://lserver/dashboard/proxy.php?executionID=".$executionID."&format=HTML4.0&streamID="
);
```

This results in image tags in the markup such as -

``` html
<img onerror="this.errored=true;" border="0" usemap="#Map24iT2" class="a38" src="http://lserver/dashboard/proxy.php?executionID=r0xady45ug3pryyu03w13iya&amp;format=HTML4.0&amp;streamID=C_24iT2_1">
```

NB I have also specified a separate Replacement root so that the report drill downs can be parsed and rendered by SSRS.

My issue comes with rendering the image using a stream.

In proxy.php 
- retrieve the ssrs object from the session.  Reset the soap client (which cannot be saved in the session).  
- Set the session Id in ssrs (execution id taken from the get variable)
- Render the stream using the format and stream id from the get variables.

The result is an empty response. 

``` php
 $ssrs = $_SESSION['ssrs'];

    $ssrs->resetSoapExecution();

    $format = $_GET['format'];

    $streamId = $_GET['streamID'];

    $ssrs->setSessionId($_GET['executionID']);

    $response = $ssrs->renderStream($format, $streamId);

    header('Content-type: ' . $response->MimeType);
    header('Cache-Control: no-cache');
    header('Pragma: no-cache');
    echo ($response->Result);
```

Have I correctly identified the stream id ?  

I have very little knowledge of the reporting services api and so am not sure to progress in debugging this problem.  I suspect I am missing something which will be obvious to someone more knowledgeable !

Thank you,
Andy

**Comment by arronwoods** [comment]
Hey Andy,

That all looks pretty similar to what we were doing. I'm no SSRS expert either, we built php-ssrs using trial and error and the SSRS docs (but found trial & error more informative in most cases). ;)

It looks like we use the execution ID from the report to grab the stream, is $_GET['streamID'] identical to the execution ID used for generating the report?

The other weird thing, and I can't remember why (sorry) but for images we do this instead:

``` php
$response = $ssrs->renderResource($format, array('GetImage' => $streamId));
```

IIRC, streams and resources are different things? If that still doesn't work, which version of SSRS are you running?

**Comment by acpbytron** [comment]
Hi, 

Thanks for getting back to me.

I have looked at using renderResource but could only find getRenderResource() in the class.  When I tried this it returned an empty data set. I looked at the device info being passed to the server in renderParams I found it had been truncated ..

```
array(2) { ["Format"]=> string(7) "HTML4.0" ["DeviceInfo"]=> string(78) "180c0b2a57f54c45bcb9e9c82754db21" } 
```

Where  180c0b2a57f54c45bcb9e9c82754db21 is the streamID.

I did try modifying renderParams to include the correct DeviceInfo - GetImage as suggested about but this also results in an empty response.

I am working against ssrs 2008 r2 and according to the documentation the services used by the php library should work with this version.

Thanks.
Andy

**Comment by arronwoods** [comment]
Hi Andy,

Sorry I've not been much use, I'll try to get a working code sample sorted for you in the next few days. I may not have access to an SSRS server any more though, I don't suppose you can provide me with read-only access to your environment via private message if necessary?

Thanks,

Arron

**Comment by acpbytron** [comment]
Thank you for your help.  I created a work-around by retrieving the images using curl with a windows basic authentication header.
