### ISSUE TITLE
Wrong namespace for SimpleXMLElement in file ServerException.php

### ISSUE THREAD

**Issue by SmokeyBrandie** [ChartBlocks/php-ssrs#6]
From my point of view the namespace for 
SimpleXMLElement in file "ServerException.php",  Line 12 
should be declared by "\"

Ending up with: 
$xml = new \SimpleXMLElement($string);

**Comment by arronwoods** [comment]
Hey,

Thanks for the feedback - we converted the lib from non-namespaced to namespaced in a bit of a hurry, seem to have missed a few bits.

Appreciate you letting us know. The fix has been applied to tag 1.0.6, which also fixes issue #7.
