### ISSUE TITLE
Check if folder is writebale is on parent instead of the folder itself 

### ISSUE THREAD

**Issue by SmokeyBrandie** [ChartBlocks/php-ssrs#8]
NTLM.php Method "setCachePath"

If cache folder has been set to "d:/tmp" (using sys_get_temp_dir() method, for example)
this line: 
$folder = dirname($path);
will return  "d:/" and check if this folder is writeable.

That means that the writeable check will be made on the parent folder instead of the cache folder itself.

**Comment by arronwoods** [comment]
I think the issue here might be the method name. It's "setCachePath" but
it's expecting a file not a directory.

The class caches the WSDL file only.

Better documentation required? Or rename and alias the old method?

**Comment by arronwoods** [comment]
I changed the method argument to $file instead of $path, but otherwise its still a bit misleading. Its a public method so will have to leave it for now.
