### ISSUE TITLE
undefined function

### ISSUE THREAD

**Issue by antonyferguson** [ChartBlocks/php-ssrs#9]
Hi,

I get the following error when trying to use your library

PHP Fatal error:  Call to undefined function SSRS\Soap\curl_init() in /var/www/vhosts/ccd/include/vendor/chartblocks/php-ssrs/library/SSRS/Soap/NTLM.php on line 124

What am I doing wrong?

Regards

**Comment by arronwoods** [comment]
Hi Anthony,

It sounds like you might need to install/enable the php curl module.

If you're using Ubuntu, the package name is php5-curl.

http://php.net/manual/en/curl.installation.php

Try that and let us know?

Hi,

I get the following error when trying to use your library

PHP Fatal error: Call to undefined function SSRS\Soap\curl_init() in
/var/www/vhosts/ccd/include/vendor/chartblocks/php-ssrs/library/SSRS/Soap/NTLM.php
on line 124

What am I doing wrong?

Regards

—
Reply to this email directly or view it on GitHub
https://github.com/ChartBlocks/php-ssrs/issues/9.

**Comment by antonyferguson** [comment]
Hi Rb

Thanks for the reply,
I have now installed CURL and now I get another error, so we are slowly make some progress.

Here is the other error
 PHP Fatal error:  Class 'SSRS\Soap\SimpleXMLElement' not found in /var/www/vhosts/ccd/include/vendor/chartblocks/php-ssrs/library/SSRS/Soap/ServerException.php on line 12

Thanks

**Comment by arronwoods** [comment]
Ah, that was fixed yesterday in issue #6 or #7. If you grab the latest
version you should get past that error!

**Comment by antonyferguson** [comment]
Hi RB

Ok updated the server with the new code now I get the following:

[Thu Mar 05 23:10:52.972275 2015] [:error] [pid 1384] [client 192.168.33.202:52055] PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /var/www/vhosts/ccd/include/vendor/chartblocks/php-ssrs/library/SSRS/Soap/ServerException.php:12\nStack trace:\n#0 /var/www/vhosts/ccd/include/vendor/chartblocks/php-ssrs/library/SSRS/Soap/ServerException.php(12): SimpleXMLElement->__construct('<!DOCTYPE HTML ...')\n#1 /var/www/vhosts/ccd/include/vendor/chartblocks/php-ssrs/library/SSRS/Soap/NTLM.php(148): SSRS\Soap\ServerException::fromResponse('<!DOCTYPE HTML ...')\n#2 /var/www/vhosts/ccd/include/vendor/chartblocks/php-ssrs/library/SSRS/Soap/NTLM.php(119): SSRS\Soap\NTLM->callCurl('https://hub.cra...', '<?xml version="...', 'http://schemas....')\n#3 [internal function]: SSRS\Soap\NTLM->__doRequest('<?xml version="...', 'https://hub.cra...', 'http://schemas....', 1, 0)\n#4 /var/www/vhosts/ccd/include/vendor/chartblocks/php-ssrs/library/SSRS/Report.php(207): SoapClient->__call('ListChildren', Array)\n#5 /var/www/vhosts/ccd/include/vendor/chartblocks/php-ssrs/library/SSRS/Report.php(20 in /var/www/vhosts/ccd/include/vendor/chartblocks/php-ssrs/library/SSRS/Soap/ServerException.php on line 12

**Comment by arronwoods** [comment]
OK great. That looks more like it.

That error means whatever URL you're polling is not returning XML. Is it
definitely hitting to your report server?

**Comment by antonyferguson** [comment]
Hi,

Yes definiately getting to the report server.
I have tried a modified version of the sample ListChildren.php.
I have changed the URL to my URL
Changed the Username and password.

Here is the code ...
$ssrs = new \SSRS\Report('https://hub.craigcor.co.za/ReportServer', $options);
$result = $ssrs->listChildren('/CraigCorReports/Sales', true);

I want to see the reports in the sales folder 

If I browse to the URL I have put in it prompts for the username and password.  
If I enter these then I see a directory listing.

Regards

**Comment by arronwoods** [comment]
From the stack trace it looks like the server is returning HTML:

> fromResponse('<!DOCTYPE HTML ...'

If you grab the exception and echo out the response does it give you
anything that might explain what is going on?

I believe you must enable the SOAP service in SSRS also, if it's not
enabled that could explain why you're getting HTML back.

If all else fails would you be willing to email me read-only credentials so
I can try connecting from here?

**Comment by antonyferguson** [comment]
Ok, that make sense, but I can't find how to enable SOAP can you point me in the right direction?

**Comment by arronwoods** [comment]
Hi @antonyferguson ,

We've released a new version (1.0.8) today that is worth trying, it fixes a few critical bugs in connecting to certain versions of SSRS.
